### ISSUE TITLE
How do I use the commands?

### ISSUE THREAD

**Issue by CitrusFruit** [SpongyBot/spongybot.github.io#1]
So.. How do I format the commands? You have not explained a single thing.

I've tried with / and . and [ etc etc before the command and nothing happens.

**Comment by ducc** [comment]
Skype: `-help`
Discord: `@SpongyBot help`

If you have any questions or need help, feel free to contact me...
Skype: `joepwnsall1`
Discord: `Sponges#9409` - join the SpongyBot discord server: http://discord.gg/0hlTJkCoQ104RNB2
